### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by bonaventure** [utlib/iiif-to-go-api#2]
I'm getting a 500 internal server error when trying to access localhost:8000. Mirador is working, but the API docs are not. I ran --debug and couldn't see an issue with vagrant. The splash page works fine, but API does not work. BTW, I did not encounter this problem with omeka to go, just with iiif to go.

**Comment by dicksonlaw583** [comment]
Please try this hotfix branch and let me know if it works: https://github.com/utlib/iiif-to-go-api/tree/hotfix-api-500

**Comment by bonaventure** [comment]
@dicksonlaw583 Yes, that hotfix did the trick! Thank you.

**Comment by dicksonlaw583** [comment]
Thank you for your confirmation. Merging now.
